# Makefile

RM = rm -f
CXX = arm-linux-g++
CXXFLAGS = -Wall -g -static
INCLUDE = -I.. -I/usr/local/arm-boost/include
LDFLAGS =  -static -lboost_program_options 
LDPATH = -L/usr/local/arm/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/bin/ \
		 -L/usr/local/arm/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/lib/gcc/arm-fsl-linux-gnueabi/4.6.2/ \
		 -L/usr/local/arm/gcc-4.6.2-glibc-2.13-linaro-multilib-2011.12/fsl-linaro-toolchain/arm-fsl-linux-gnueabi/multi-libs/armv7-a/default/lib32 \
		 -L/usr/local/arm-boost/lib

VPATH = ..

PROGS =	parse_command_line parse_environment parse_config_file parse_all

.PHONY: all
all: $(PROGS)
	@echo "build OK!"

clean:
	@$(RM) $(PROGS) *.o
	@echo "clean OK!"

%.o:%.cpp
	$(CXX) -o $@ -c $< $(CXXFLAGS) $(INCLUDE)

parse_command_line: config_parser.o config_parser_util.o parse_command_line.o
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDPATH)

parse_environment: config_parser.o config_parser_util.o parse_environment.o
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDPATH)

parse_config_file: config_parser.o config_parser_util.o parse_config_file.o
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDPATH)

parse_all: config_parser.o config_parser_util.o parse_all.o
	$(CXX) -o $@ $^ $(LDFLAGS) $(LDPATH)

